// Mock data for testing (will be replaced with API calls later)
export const mockCategories = [
  { id: 1, name: 'Dog Food', color: '#FF5722' },
  { id: 2, name: 'Cat Food', color: '#2196F3' },
  { id: 3, name: 'Bird Food', color: '#4CAF50' },
  { id: 4, name: 'Fish Food', color: '#9C27B0' },
  { id: 5, name: 'Small Animal', color: '#FF9800' },
  { id: 6, name: 'Reptile Food', color: '#795548' },
  { id: 7, name: 'Horse Food', color: '#607D8B' },
  { id: 8, name: 'Pet Treats', color: '#E91E63' },
  { id: 9, name: 'Pet Supplements', color: '#00BCD4' },
  { id: 10, name: 'Pet Accessories', color: '#8BC34A' },
];

export const mockProducts = [
  {
    id: 1,
    productname: 'Premium Dog Food Natural',
    productNameL1: 'Premium Dog',
    productNameL2: 'Food Natural',
    productprice: 4999, // $49.99 in cents
    sku: 'PDF001',
    barcodes: ['5901234123457'],
    productIngredients: 'Chicken, Rice, Vegetables, Vitamins, Minerals',
    productStorageInstructions: '100% NATURAL\\nNO ARTIFICIAL COLOURS\\nWA OWNED',
    productSize: 10,
    productUnit: 'kg',
    expirationDuration: 12,
    expirationType: 'months',
    category: 1,
  },
  {
    id: 2,
    productname: 'Organic Cat Food',
    productNameL1: 'Organic Cat',
    productNameL2: 'Food',
    productprice: 3999, // $39.99 in cents
    sku: 'OCF002',
    barcodes: ['4007817324035'],
    productIngredients: 'Salmon, Brown Rice, Carrots, Essential Nutrients',
    productStorageInstructions: '100% NATURAL\\nNO ARTIFICIAL COLOURS\\nWA OWNED',
    productSize: 5,
    productUnit: 'kg',
    expirationDuration: 10,
    expirationType: 'months',
    category: 2,
  },
  {
    id: 3,
    productname: 'Gourmet Cat Food',
    productNameL1: 'Gourmet Cat',
    productNameL2: 'Food',
    productprice: 399, // $3.99 in cents
    sku: 'GCF003',
    barcodes: ['7622210244154'],
    productIngredients: 'Tuna, Water, Fish Oil, Vitamins, Minerals',
    productStorageInstructions: '100% NATURAL\\nNO ARTIFICIAL COLOURS\\nUSE WITHIN 2 DAYS',
    productSize: 400,
    productUnit: 'g',
    expirationDuration: 25,
    expirationType: 'days',
    category: 2,
  },
  {
    id: 4,
    productname: 'Bird Seed Mix',
    productNameL1: 'Bird Seed',
    productNameL2: 'Mix',
    productprice: 1299, // $12.99 in cents
    sku: 'BSM004',
    barcodes: ['8001250123459'],
    productIngredients: 'Sunflower Seeds, Millet, Canary Seed, Oats',
    productStorageInstructions: '100% NATURAL\\nNO ARTIFICIAL COLOURS\\nKEEP SEALED',
    productSize: 2,
    productUnit: 'kg',
    expirationDuration: 8,
    expirationType: 'months',
    category: 3,
  },
  {
    id: 5,
    productname: 'Tropical Fish Flakes',
    productNameL1: 'Tropical',
    productNameL2: 'Fish Flakes',
    productprice: 899, // $8.99 in cents
    sku: 'TFF005',
    barcodes: ['9780201379624'],
    productIngredients: 'Fish Meal, Shrimp Meal, Wheat Flour, Fish Oil',
    productStorageInstructions: '100% NATURAL\\nNO ARTIFICIAL COLOURS\\nKEEP SEALED',
    productSize: 250,
    productUnit: 'g',
    expirationDuration: 9,
    expirationType: 'months',
    category: 4,
  },
  {
    id: 6,
    productname: 'Guinea Pig Pellets',
    productNameL1: 'Guinea Pig',
    productNameL2: 'Pellets',
    productprice: 1599, // $15.99 in cents
    sku: 'GPP006',
    barcodes: ['6421691236458'],
    productIngredients: 'Timothy Hay, Alfalfa, Oats, Barley, Vitamins',
    productStorageInstructions: '100% NATURAL\\nNO ARTIFICIAL COLOURS\\nKEEP SEALED',
    productSize: 3,
    productUnit: 'kg',
    expirationDuration: 7,
    expirationType: 'months',
    category: 5,
  },
  {
    id: 7,
    productname: 'Reptile Food Sticks',
    productNameL1: 'Reptile Food',
    productNameL2: 'Sticks',
    productprice: 1999, // $19.99 in cents
    sku: 'RFS007',
    barcodes: ['3800043510850'],
    productIngredients: 'Fish Meal, Wheat Flour, Vitamins, Minerals',
    productStorageInstructions: '100% NATURAL\\nNO ARTIFICIAL COLOURS\\nKEEP SEALED',
    productSize: 500,
    productUnit: 'g',
    expirationDuration: 6,
    expirationType: 'months',
    category: 6,
  },
  {
    id: 8,
    productname: 'Premium Horse Feed',
    productNameL1: 'Premium',
    productNameL2: 'Horse Feed',
    productprice: 5999, // $59.99 in cents
    sku: 'PHF008',
    barcodes: ['8712345678906'],
    productIngredients: 'Oats, Barley, Alfalfa, Minerals, Vitamins',
    productStorageInstructions: '100% NATURAL\\nNO ARTIFICIAL COLOURS\\nKEEP SEALED',
    productSize: 20,
    productUnit: 'kg',
    expirationDuration: 8,
    expirationType: 'weeks',
    category: 7,
  },
  {
    id: 9,
    productname: 'Dog Chicken Treats',
    productNameL1: 'Dog Chicken',
    productNameL2: 'Treats',
    productprice: 999, // $9.99 in cents
    sku: 'DCT009',
    barcodes: ['9501101530003'],
    productIngredients: 'Chicken, Wheat Flour, Vegetable Oil, Vitamins',
    productStorageInstructions: '100% NATURAL\\nNO ARTIFICIAL COLOURS\\nSEAL AFTER OPENING',
    productSize: 500,
    productUnit: 'g',
    expirationDuration: 1,
    expirationType: 'years',
    category: 8,
  },
  {
    id: 10,
    productname: 'Joint Health Supplement',
    productNameL1: 'Joint Health',
    productNameL2: 'Supplement',
    productprice: 2499, // $24.99 in cents
    sku: 'JHS010',
    barcodes: ['5012345678900'],
    productIngredients: 'Glucosamine, Chondroitin, MSM, Vitamin C',
    productStorageInstructions: '100% NATURAL\\nNO ARTIFICIAL COLOURS\\nKEEP SEALED',
    productSize: 250,
    productUnit: 'g',
    expirationDuration: 18,
    expirationType: 'months',
    category: 9,
  },
];

export const mockAppData = {
  categories: mockCategories,
  products: mockProducts,
  printerStatus: 'ready', // 'ready', 'printing', 'error', 'systemError'
}; 