// Mock data for testing (will be replaced with API calls later)
export const mockCategories = [
  { id: 1, name: 'Dog Food', color: '#FF5722' },
  { id: 2, name: 'Cat Food', color: '#2196F3' },
  { id: 3, name: 'Bird Food', color: '#4CAF50' },
  { id: 4, name: 'Fish Food', color: '#9C27B0' },
  { id: 5, name: 'Small Animal', color: '#FF9800' },
  { id: 6, name: 'Reptile Food', color: '#795548' },
  { id: 7, name: 'Horse Food', color: '#607D8B' },
  { id: 8, name: 'Pet Treats', color: '#E91E63' },
  { id: 9, name: 'Pet Supplements', color: '#00BCD4' },
  { id: 10, name: 'Pet Accessories', color: '#8BC34A' },
];

export const mockProducts = [
  {
    id: 1,
    name: 'Premium Dog Food',
    category: 1,
    type: 'Dry Food',
    weight: '10kg',
    price: '$49.99',
    ingredients: 'Chicken, Rice, Vegetables, Vitamins, Minerals',
    ingredientsLine1: 'Chicken, Rice, Peas, Sweet Potato',
    ingredientsLine2: 'Fish Oil, Vitamins A, D, E, K',
    ingredientsLine3: 'Natural Preservatives, Made in Australia',
    expirationDuration: 12,
    expirationType: 'months',
    storageInstructions: '100% NATURAL\nNO ARTIFICIAL COLOURS\nMIXED AND PRODUCED IN AUSTRALIA\nSeal after opening',
    barcode: '5901234123457',
  },
  {
    id: 2,
    name: 'Organic Cat Food',
    category: 2,
    type: 'Dry Food',
    weight: '5kg',
    price: '$39.99',
    ingredients: 'Salmon, Brown Rice, Carrots, Essential Nutrients',
    ingredientsLine1: 'Wild Salmon, Brown Rice, Carrots',
    ingredientsLine2: 'Taurine, Omega-3 Fatty Acids',
    ingredientsLine3: 'No Artificial Colors or Preservatives',
    expirationDuration: 10,
    expirationType: 'months',
    storageInstructions: '100% NATURAL\nNO ARTIFICIAL COLOURS\nMIXED AND PRODUCED IN AUSTRALIA\nSeal after opening',
    barcode: '4007817324035',
  },
  {
    id: 3,
    name: 'Gourmet Cat Food',
    category: 2,
    type: 'Wet Food',
    weight: '400g',
    price: '$3.99',
    ingredients: 'Tuna, Water, Fish Oil, Vitamins, Minerals',
    ingredientsLine1: 'Tuna (65%), Water, Fish Broth',
    ingredientsLine2: 'Sunflower Oil, Vitamin E, Zinc',
    ingredientsLine3: 'Sustainably Caught, Dolphin Safe',
    expirationDuration: 25,
    expirationType: 'days',
    storageInstructions: '100% NATURAL\nNO ARTIFICIAL COLOURS\nMIXED AND PRODUCED IN AUSTRALIA\nUse within 2 days',
    barcode: '7622210244154',
  },
  {
    id: 4,
    name: 'Bird Seed Mix',
    category: 3,
    type: 'Seed Mix',
    weight: '2kg',
    price: '$12.99',
    ingredients: 'Sunflower Seeds, Millet, Canary Seed, Oats',
    ingredientsLine1: 'Sunflower Seeds, Millet, Canary Seed',
    ingredientsLine2: 'Oats, Dried Fruits, Nyjer Seeds',
    ingredientsLine3: 'No Added Sugar or Preservatives',
    expirationDuration: 8,
    expirationType: 'months',
    storageInstructions: '100% NATURAL\nNO ARTIFICIAL COLOURS\nMIXED AND PRODUCED IN AUSTRALIA\nKeep sealed',
    barcode: '8001250123459',
  },
  {
    id: 5,
    name: 'Tropical Fish Flakes',
    category: 4,
    type: 'Fish Food',
    weight: '250g',
    price: '$8.99',
    ingredients: 'Fish Meal, Shrimp Meal, Wheat Flour, Fish Oil, Vitamins',
    ingredientsLine1: 'Fish Meal, Shrimp Meal, Wheat Flour',
    ingredientsLine2: 'Fish Oil, Spirulina, Beta Carotene',
    ingredientsLine3: 'Enhanced Color Formula, Vita-Blend',
    expirationDuration: 9,
    expirationType: 'months',
    storageInstructions: '100% NATURAL\nNO ARTIFICIAL COLOURS\nMIXED AND PRODUCED IN AUSTRALIA\nKeep sealed',
    barcode: '9780201379624',
  },
  {
    id: 6,
    name: 'Guinea Pig Pellets',
    category: 5,
    type: 'Small Animal Food',
    weight: '3kg',
    price: '$15.99',
    ingredients: 'Timothy Hay, Alfalfa, Oats, Barley, Vitamins',
    ingredientsLine1: 'Timothy Hay, Alfalfa, Oats, Barley',
    ingredientsLine2: 'Flaxseed, Vitamin C Supplement',
    ingredientsLine3: 'High Fiber Formula, No Artificial Colors',
    expirationDuration: 7,
    expirationType: 'months',
    storageInstructions: '100% NATURAL\nNO ARTIFICIAL COLOURS\nMIXED AND PRODUCED IN AUSTRALIA\nKeep sealed',
    barcode: '6421691236458',
  },
  {
    id: 7,
    name: 'Reptile Food Sticks',
    category: 6,
    type: 'Reptile Food',
    weight: '500g',
    price: '$19.99',
    ingredients: 'Fish Meal, Wheat Flour, Vitamins, Minerals',
    ingredientsLine1: 'Fish Meal (40%), Wheat Flour, Krill',
    ingredientsLine2: 'Calcium Carbonate, Vitamin D3',
    ingredientsLine3: 'Floating Formula, Complete Nutrition',
    expirationDuration: 6,
    expirationType: 'months',
    storageInstructions: '100% NATURAL\nNO ARTIFICIAL COLOURS\nMIXED AND PRODUCED IN AUSTRALIA\nKeep sealed',
    barcode: '3800043510850',
  },
  {
    id: 8,
    name: 'Premium Horse Feed',
    category: 7,
    type: 'Horse Food',
    weight: '20kg',
    price: '$59.99',
    ingredients: 'Oats, Barley, Alfalfa, Minerals, Vitamins',
    ingredientsLine1: 'Oats, Barley, Alfalfa, Molasses',
    ingredientsLine2: 'Soybean Meal, Flaxseed, Biotin',
    ingredientsLine3: 'Performance Formula, Hoof Support',
    expirationDuration: 8,
    expirationType: 'weeks',
    storageInstructions: '100% NATURAL\nNO ARTIFICIAL COLOURS\nMIXED AND PRODUCED IN AUSTRALIA\nKeep sealed',
    barcode: '8712345678906',
  },
  {
    id: 9,
    name: 'Dog Treats - Chicken Flavor',
    category: 8,
    type: 'Dog Treats',
    weight: '500g',
    price: '$9.99',
    ingredients: 'Chicken, Wheat Flour, Vegetable Oil, Vitamins',
    ingredientsLine1: 'Chicken (60%), Wheat Flour',
    ingredientsLine2: 'Vegetable Oil, Rosemary Extract',
    ingredientsLine3: 'No Artificial Colors or Flavors',
    expirationDuration: 1,
    expirationType: 'years',
    storageInstructions: '100% NATURAL\nNO ARTIFICIAL COLOURS\nMIXED AND PRODUCED IN AUSTRALIA\nSeal after opening',
    barcode: '9501101530003',
  },
  {
    id: 10,
    name: 'Joint Health Supplement',
    category: 9,
    type: 'Pet Supplements',
    weight: '250g',
    price: '$24.99',
    ingredients: 'Glucosamine, Chondroitin, MSM, Vitamin C',
    ingredientsLine1: 'Glucosamine HCl (500mg), Chondroitin',
    ingredientsLine2: 'MSM, Vitamin C, Hyaluronic Acid',
    ingredientsLine3: 'Senior Formula, Made in Australia',
    expirationDuration: 18,
    expirationType: 'months',
    storageInstructions: '100% NATURAL\nNO ARTIFICIAL COLOURS\nMIXED AND PRODUCED IN AUSTRALIA\nKeep sealed',
    barcode: '5012345678900',
  },
];

export const mockAppData = {
  categories: mockCategories,
  products: mockProducts,
  version: '0.2.5',
  printerStatus: 'ready', // 'ready', 'printing', 'error', 'systemError'
}; 